// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMc7YM3gq8QEjRCdT-dvkhojfTU9T6NDk',
    appId: '1:90139034603:web:1bcb8fd23b9cea32af8fae',
    messagingSenderId: '90139034603',
    projectId: 'instagram-clone-a5460',
    authDomain: 'instagram-clone-a5460.firebaseapp.com',
    storageBucket: 'instagram-clone-a5460.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3__cZaNGKx0W6WO-QxqpyVqAuxeS4ouA',
    appId: '1:90139034603:android:31f940a0d5405974af8fae',
    messagingSenderId: '90139034603',
    projectId: 'instagram-clone-a5460',
    storageBucket: 'instagram-clone-a5460.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLPIr6GXD70sCObcTcouRTtAvyYO5prTw',
    appId: '1:90139034603:ios:1154ff1824cc2df4af8fae',
    messagingSenderId: '90139034603',
    projectId: 'instagram-clone-a5460',
    storageBucket: 'instagram-clone-a5460.appspot.com',
    iosClientId: '90139034603-abrufuk1r34fh776kbma29ig1oinrn2c.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramFlutter',
  );
}
